# Generated by Django 3.0.2 on 2020-02-02 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmp1', models.CharField(max_length=200, null=True)),
                ('tmp2', models.CharField(max_length=200, null=True)),
                ('tmp3', models.CharField(max_length=200, null=True)),
                ('tmp4', models.CharField(max_length=200, null=True)),
                ('tmp5', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
